### PR TITLE
Travis build matrix

### PR DESCRIPTION
**Pull request by jonallured**
I was thinking about taking a crack at #6 so I cloned the repo and started getting myself situated with the code and it occurred to me that it might make sense to provide a little more coverage for a gem like this.

### CODE REVIEW

**Comment by jonallured** [comment]
Looks like me like these tests won't pass on Rails 4.2.x:

https://travis-ci.org/artsy/artsy-auth/builds/292817006

My theory is that when this was setup, a Rails 5.x app was used and the stuff that changed from 4.2 to 5.0 is going to break. This is a tricky one because it doesn't really mean that the gem is broken for that Rails version, just that our test setup doesn't work across versions of Rails.

We could possibly address this, but before we go down that path, do we know if any of this gem's clients are on Rails 4.2? My preference would be to not worry about this if we can instead bump the requirement to 5.0.

/cc @ashkan18

**Comment by dblock** [comment]
You can just kill https://github.com/artsy/artsy-auth/blob/9fa4f1330e04b06b734ca89df18ece281e54f6ee/spec/dummy/config/environments/test.rb#L17 and things should work just fine.

**Comment by jonallured** [comment]
Yep, happy to do this, but I was trying to see if there were any users of this library on Rails 4.2 - if not, then I can also just remove that version from the matrix.

**Comment by ashkan18** [comment]
As far as i know there are no apps in Rails 4 using this, if we can fix this issue by the change @dblock suggested i would vote for that since nowhere we require rails 5. What do you think?

**Comment by jonallured** [comment]
I don't feel super strongly about this - if you feel better about this PR if I keep the 4.2 builds in there, then I'm happy to! I took out that line with 3b8e2a9 and as @dblock predicted, the builds all pass so I think this is good to go.

**Comment by jonallured** [comment]
You know how sometimes PRs fall through the cracks? I think that happened to this one - wanna merge me @ashkan18 or @dblock?

**Pull request merged**
