### PR TITLE
chore: prepare v0.2.0 release

### PR DESCRIPTION
**Pull request by starsirius**
Bump up version to v0.2.0. I'll publish a new version to rubygems and add a new release to github next.

### CODE REVIEW

**Comment by starsirius** [comment]
Oops just realized @ashkan18 (👋 ) you're the [only owner](https://rubygems.org/gems/artsy-auth) of this gem on rubygems. Can you help us add it@artsymail.com (or myself cychi1210@gmail.com) to the owners? 🙏

**Comment by ashkan18** [comment]
oh i had no idea! thanks for mentioning this! I'll do this right now! 😅

**Comment by ashkan18** [comment]
done! ✅ feel free to remove me after you or it@ joined 💜

**Comment by starsirius** [comment]
Thank you, @ashkan18! You should totally stay! 🙏

**Pull request merged**
